name: CICD Pipeline

on:
  push:
    branches:
      - main

env:
  DISCORD_TOKEN: ${{secrets.DISCORD_TOKEN}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{secrets.EC2_SSH_KEY}}

      - name: Deploy to EC2
        run: |
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" > /home/ubuntu/Syaa/.env
          ssh -o StrictHostKeyChecking=no ubuntu@${{secrets.EC2_PUBLIC_IP}} 'bash -s' < deploy.sh
